### ISSUE TITLE
dbt Reference Docs Incorrectly Suggest Support for 1.0.4 and Newer

### ISSUE THREAD

**Issue by trentwritescode** [aurany/dbt-ibmdb2#31]
[dbt Docs](https://docs.getdbt.com/reference/warehouse-setups/ibmdb2-setup) incorrectly suggest this plugin supports dbt Core v1.0.4+, yet this plugin has open issues for 1.3 and 1.4 compatibility.

**Comment by aurany** [comment]
Release 1.4.0 should solve this issue.
